# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollisionNode',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('identificador', models.IntegerField(
                    unique=True, verbose_name='Identificador')),
                ('collisions', models.ManyToManyField(
                    related_name='_collisionnode_collisions_+',
                    to='nodes.CollisionNode',
                    verbose_name='Colisões')),
            ],
            options={
                'verbose_name_plural': 'Nós de Colisões',
                'verbose_name': 'Nó de Colisão',
            },
        ),
    ]
