# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollisionEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='collisionnode',
            old_name='identificador',
            new_name='identifier',
        ),
        migrations.RemoveField(
            model_name='collisionnode',
            name='collisions',
        ),
        migrations.AddField(
            model_name='collisionedge',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='nodes.CollisionNode'),
        ),
        migrations.AddField(
            model_name='collisionedge',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinies', to='nodes.CollisionNode'),
        ),
    ]
