# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20170129_2143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collisionedge',
            unique_together=set([('from_node', 'to_node')]),
        ),
    ]
